//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for Java 2001 by Jonathan Pierce &amp; Mike Krueger --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;Java&quot; extensions=&quot;.java&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;MethodName&quot; foreground=&quot;#FF09D5&quot; /&gt;
        ///  &lt;Color name=&quot;Digits&quot; foreground=&quot;#11D500&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;#FFE0580E&quot;  /&gt;
        ///  &lt;Color name=&quot;Character&quot; foreground=&quot;Magenta&quot;  /&gt;
        ///  &lt;Color name=&quot;Comment&quot; f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Java_DarkMode {
            get {
                return ResourceManager.GetString("Java_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for Java 2001 by Jonathan Pierce &amp; Mike Krueger --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;Java&quot; extensions=&quot;.java&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;MethodName&quot; foreground=&quot;#FF09D5&quot; /&gt;
        ///  &lt;Color name=&quot;Digits&quot; foreground=&quot;#11D500&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;#FFE0580E&quot;  /&gt;
        ///  &lt;Color name=&quot;Character&quot; foreground=&quot;Magenta&quot;  /&gt;
        ///  &lt;Color name=&quot;Comment&quot; f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Java_LightMode {
            get {
                return ResourceManager.GetString("Java_LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for Java 2001 by Jonathan Pierce &amp; Mike Krueger --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;Java&quot; extensions=&quot;.java&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;MethodName&quot; foreground=&quot;#FF09D5&quot; /&gt;
        ///  &lt;Color name=&quot;Digits&quot; foreground=&quot;#11D500&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;#FFE0580E&quot;  /&gt;
        ///  &lt;Color name=&quot;Character&quot; foreground=&quot;Magenta&quot;  /&gt;
        ///  &lt;Color name=&quot;Comment&quot; f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Python_DarkMode {
            get {
                return ResourceManager.GetString("Python_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for Java 2001 by Jonathan Pierce &amp; Mike Krueger --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;Java&quot; extensions=&quot;.java&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;MethodName&quot; foreground=&quot;#FF09D5&quot; /&gt;
        ///  &lt;Color name=&quot;Digits&quot; foreground=&quot;#11D500&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;#FFE0580E&quot;  /&gt;
        ///  &lt;Color name=&quot;Character&quot; foreground=&quot;Magenta&quot;  /&gt;
        ///  &lt;Color name=&quot;Comment&quot; f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Python_LightMode {
            get {
                return ResourceManager.GetString("Python_LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WordWrap {
            get {
                object obj = ResourceManager.GetObject("WordWrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for Java 2001 by Jonathan Pierce &amp; Mike Krueger --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;Java&quot; extensions=&quot;.java&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;MethodName&quot; foreground=&quot;#FF09D5&quot; /&gt;
        ///  &lt;Color name=&quot;Digits&quot; foreground=&quot;#11D500&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;#FFE0580E&quot;  /&gt;
        ///  &lt;Color name=&quot;Character&quot; foreground=&quot;Magenta&quot;  /&gt;
        ///  &lt;Color name=&quot;Comment&quot; f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_DarkMode {
            get {
                return ResourceManager.GetString("XML_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!-- syntaxdefinition for Java 2001 by Jonathan Pierce &amp; Mike Krueger --&gt;
        ///&lt;!-- converted to AvalonEdit format by Siegfried Pammer in 2010 --&gt;
        ///&lt;SyntaxDefinition name=&quot;Java&quot; extensions=&quot;.java&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;MethodName&quot; foreground=&quot;#FF09D5&quot; /&gt;
        ///  &lt;Color name=&quot;Digits&quot; foreground=&quot;#11D500&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;#FFE0580E&quot;  /&gt;
        ///  &lt;Color name=&quot;Character&quot; foreground=&quot;Magenta&quot;  /&gt;
        ///  &lt;Color name=&quot;Comment&quot; f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML_LightMode {
            get {
                return ResourceManager.GetString("XML_LightMode", resourceCulture);
            }
        }
    }
}
